version: '2'
services:

  web:
    build: .
    ports:
      - "8080:80"
      - "443:443"
    links:
      - mysql
    volumes:
      - ./www:/var/www
      - ./logs:/var/log

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456